### ISSUE TITLE
Component paths should be specific

### ISSUE THREAD

**Issue by dotnil** [erzu/porter#36]
Currently all three paths can access `home.js`:

```
/porter-app/1.0.0/home.js
/porter-app/home.js
/home.js
```

However, `/porter-app/home.js` shouldn't be available since it causes chaos in following scenario:

```js
// home.js
require('../foo')
```

When loader resolves `../foo` above, the context is `porter-app/1.0.0/home`. The resolved module id will be `porter-app/foo`, which is accessible in development (because porter middleware handles that), but not available in production due to there's no `../foo` actually. 

I think the middleware should only allow two types of paths:

```
/porter-app/1.0.0/home.js
/home.js
```

The latter one is for main scripts, `<script src="/home.js"></script>` is much easier to write. After `home.js` loads, and the loader kicks in, all components and modules loaded later will have their versions specified.

**Comment by daiheitan** [comment]
![webwxgetmsgimg](https://user-images.githubusercontent.com/4921289/35626185-e01563be-06cf-11e8-8344-71d98ef09b60.gif)
